### ISSUE TITLE
Google search shows lack of crawled metadata

### ISSUE THREAD

**Issue by mccamon** [interledger/interledger-website#31]
<img width="214" alt="google-search" src="https://user-images.githubusercontent.com/2854602/123324289-43d7df00-d4fc-11eb-97cb-5299aec4e2ef.PNG">

From incognito when you search "Interledger Foundation" the crawled data is empty. Upon further review it does look like the site hasn't been indexed since 2015.

**Comment by nathanielfostanperry** [comment]
@mccamon We pushed an update that should resolve this issue. It may take some time for google to crawl the site again however.

**Comment by mccamon** [comment]
Verified robots.txt file is now working properly.

**Comment by AlexLakatos** [comment]
The current [robots.txt](https://interledger.org/robots.txt) file reverted back and is not allowing any pages on the site to be crawled because it uses `Disallow: /`.

<img width="343" alt="Screenshot 2021-07-13 at 13 50 40" src="https://user-images.githubusercontent.com/690132/125454634-9b6677b2-22f4-44a9-a80b-6a91e3839ccd.png">
