### ISSUE TITLE
Increase font 

### ISSUE THREAD

**Issue by bmarbury** [interledger/interledger-website#8]
- Can the font for the featured programs starting at Distributed Media Lab and ending at GftW Ambassador be increased
- Under our work and the focus areas: financial inclusion, Open Payments, and Web Monetization be increased
- On the take action page under For Content Creators and Users, can the fonts for all of the ILP enabled applications be increased?  Basically all of the text that has boxes on that page need to be increased.  But also the text under Partner With Us

**Comment by tbeck** [comment]
Hi @bmarbury 
Thanks for outlining the areas of concern. We will make adjustments and push to staging for review.
Because of the nature of style inheritance and responsive considerations, the changes we make will have an effect on other copy sections in the site beyond the areas that you outlined. This is most likely expected, but I am mentioning now so that we review and test across devices before pushing changes live.

We will post a link here for review when ready.

Thanks!

**Comment by bmarbury** [comment]
Looks good.  Thanks!
